echo "NOTE:"
echo "If you are using terminals connected through SSH, make sure that you are connected to the same machine"
echo "For example, if running:"
echo "ssh <netlink>@ugls.ece.uvic.ca"
echo "puts you on machine ugls13, then for the rest of your terminals, connect with:"
echo "ssh <netlink>@ugls13.ece.uvic.ca"
echo ""

echo "Chatroom:"
echo "Start the server in any terminal using the command"
echo "$ INSTALL_DIR/chat_server"
echo "Next, in N terminals (where N is the desired number of clients), run the following command"
echo "$ INSTALL_DIR/chat_client"
echo "Your chatroom will now be populated with all of the clients and you can use the client terminals to send messages."
echo "Send the #help command to get a list of possible commands that can be used (besides just sending normal messages)."
echo "To shutdown the server, simply use CTRL+C on the server terminal."
echo "To shutdown any clients, you can use CTRL+C or you can use the #exit command."


echo ""
echo "Connect4 Game:"
echo "Start the server in any terminal using the command"
echo "$ INSTALL_DIR/connect4_server"
echo "Next, in N terminals (where N is the desired number of clients), run the following command"
echo "$ INSTALL_DIR/connect4_client"
echo "Whenver there are 2 clients that are not already in a game, they will be placed in a game together."
echo "Send the #help command to get a list of possible commands that can be used."
echo "To shutdown the server or client, simply use CTRL+C on the appropriate terminal."
echo ""

echo "For more information, refer to the README.txt or the comments at the top of each cpp / hpp file."